### ISSUE TITLE
internal modules missing from "provides"

### ISSUE THREAD

**Issue by timo** [slobo/Six11#4]
Inside "X11::Xlib::Raw", the code immediately uses "X11::Xlib::Raw::X", which doesn't appear in the "provides" section of the META6.json, which causes it to not find it.

**Comment by slobo** [comment]
Hi @timo , how do I reproduce this problem? Is it related to a package manager? 
Thanks and sorry for delay; just saw this now - having trouble managing my inbox it seems...

**Comment by timo** [comment]
right, it's related to package management.

when installing it with zef and you then try `perl6 -e 'use X11::Xlib::Raw'`, you get "Could not find X11::Xlib::Raw::X at line 5 in: […]" because you can only `use` something from an installed module when it's in a "provides" section somewhere

**Comment by slobo** [comment]
So turns out that `panda install` does not set exit code on error and the problem was there in travis logs all along, but went unnoticed since builds still passed. Tsk tsk, bad panda.

I've added missing provides, and told travis to use `zef install` since that actually barfs in expected way.

Please reopen the issue if it comes back. Thanks again!
